//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaERP.DAL.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_LineVersion : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Users",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Suppliers",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "PurchaseOrders",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "PurchaseLines",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Products",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Orders",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "OrderLines",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Invoices",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "InvoiceLines",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Employees",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Departments",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Customers",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AddColumn<uint>(
                name: "xmin",
                schema: "nexa_erp",
                table: "Categories",
                type: "xid",
                rowVersion: true,
                nullable: false,
                defaultValue: 0u);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Suppliers");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "PurchaseOrders");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "PurchaseLines");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Products");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "OrderLines");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Invoices");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "InvoiceLines");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Departments");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "xmin",
                schema: "nexa_erp",
                table: "Categories");
        }
    }
}
