//<auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexaERP.DAL.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_UserId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                    DELETE FROM nexa_erp."PurchaseOrders";
                    DELETE FROM nexa_erp."Orders";
                """);
            migrationBuilder.AddColumn<Guid>(
                name: "user_id",
                schema: "nexa_erp",
                table: "PurchaseOrders",
                type: "uuid",
                maxLength: 500,
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "user_id",
                schema: "nexa_erp",
                table: "Orders",
                type: "uuid",
                maxLength: 500,
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateIndex(
                name: "ix_purchase_orders_user_id",
                schema: "nexa_erp",
                table: "PurchaseOrders",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_orders_user_id",
                schema: "nexa_erp",
                table: "Orders",
                column: "user_id");

            migrationBuilder.AddForeignKey(
                name: "fk_orders_users_user_id",
                schema: "nexa_erp",
                table: "Orders",
                column: "user_id",
                principalSchema: "nexa_erp",
                principalTable: "Users",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "fk_purchase_orders_users_user_id",
                schema: "nexa_erp",
                table: "PurchaseOrders",
                column: "user_id",
                principalSchema: "nexa_erp",
                principalTable: "Users",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_orders_users_user_id",
                schema: "nexa_erp",
                table: "Orders");

            migrationBuilder.DropForeignKey(
                name: "fk_purchase_orders_users_user_id",
                schema: "nexa_erp",
                table: "PurchaseOrders");

            migrationBuilder.DropIndex(
                name: "ix_purchase_orders_user_id",
                schema: "nexa_erp",
                table: "PurchaseOrders");

            migrationBuilder.DropIndex(
                name: "ix_orders_user_id",
                schema: "nexa_erp",
                table: "Orders");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "nexa_erp",
                table: "PurchaseOrders");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "nexa_erp",
                table: "Orders");
        }
    }
}
