services:
  nexaerp.api:
    image: ${DOCKER_REGISTRY-}nexaerpapi
    build:
      context: .
      dockerfile: src/NexaERP.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://nexaerp.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc

  nexaerp.postgres:
      image: postgres:17.2 # or latest
      environment:
        POSTGRES_DB: nexaerp
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - ./.containers/postgres_data:/var/lib/postgresql/data
      ports:
        - 5432:5432

  nexaerp.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888

  nexaerp.redis:
    image: redis:latest
    container_name: NexaERP.Redis
    restart: always
    ports:
      - "6379:6379"