using System.IdentityModel.Tokens.Jwt;
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using NexaERP.DAL.Context;
using NexaERP.DAL.Database;
using NexaERP.DAL.Identity;
using NexaERP.DAL.Repositories.Abstraction;
using NexaERP.DAL.Repositories.Implementation;
using NexaERP.DAL.Services;
using NexaERP.DAL.Settings;

namespace NexaERP.DAL;

public static class DependencyInjection
{
    // Registers repositories and infrastructure services.
    public static IServiceCollection AddInfrastructure(
        this IServiceCollection services)
    {
        // Register generic repository.
        services.AddScoped(typeof(IGenericRepository<>), typeof(GenericRepository<>));

        // Register Unit of Work.
        services.AddScoped<IUnitOfWork>(
            sp => sp.GetRequiredService<ApplicationDbContext>());

        // Register repositories.
        services.AddScoped<ICustomerRepository, CustomerRepository>();
        services.AddScoped<ICategoryRepository, CategoryRepository>();
        services.AddScoped<IProductRepository, ProductRepository>();
        services.AddScoped<ISupplierRepository, SupplierRepository>();
        services.AddScoped<IPurchaseOrderRepository, PurchaseOrderRepository>();
        services.AddScoped<IOrderRepository, OrderRepository>();
        services.AddScoped<IInvoiceRepository, InvoiceRepository>();
        services.AddScoped<IEmployeeRepository, EmployeeRepository>();
        services.AddScoped<IDepartmentRepository, DepartmentRepository>();
        services.AddScoped<IUserRepository, UserRepository>();
        services.AddScoped<IRefreshTokenRepository, RefreshTokenRepository>();

        services.AddMemoryCache();
        services.AddScoped<UserContext>();
        return services;
    }

    // Registers the database context.
    public static IServiceCollection AddDatabase(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        services.AddDbContext<ApplicationDbContext>(options =>
            options.UseNpgsql(
                configuration.GetConnectionString("Database"),
                npgsqlOptions =>
                    npgsqlOptions.MigrationsHistoryTable(
                        HistoryRepository.DefaultTableName,
                        Schemas.Application))
            .UseSnakeCaseNamingConvention());

        services.AddDbContext<ApplicationIdentityDbContext>(options =>
            options.UseNpgsql(
                configuration.GetConnectionString("Database"),
                npgsqlOptions =>
                    npgsqlOptions.MigrationsHistoryTable(
                        HistoryRepository.DefaultTableName,
                        Schemas.Identity))
            .UseSnakeCaseNamingConvention());

        return services;
    }

    /// <summary>
    /// Configures ASP.NET Core Identity + JWT authentication.
    /// </summary>
    public static IServiceCollection AddAuthenticationService(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        services
            // Registers ASP.NET Core Identity with default user & role entities
            .AddIdentity<IdentityUser, IdentityRole>()
            // Configures EF Core store for Identity
            .AddEntityFrameworkStores<ApplicationIdentityDbContext>();

        // Bind Jwt settings from configuration (appsettings.json → Jwt section)
        services.Configure<JwtAuthOptions>(
            configuration.GetSection("Jwt"));

        // Retrieve strongly typed Jwt settings
        JwtAuthOptions jwtAuthOptions =
            configuration.GetSection("Jwt").Get<JwtAuthOptions>()!;

        services
            // Configures authentication services and sets default schemes
            // DefaultAuthenticateScheme → used when validating incoming requests
            // DefaultChallengeScheme → used when returning 401 Unauthorized responses
            .AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            // Registers JWT Bearer authentication handler
            // This enables the API to accept tokens via:
            // Authorization: Bearer {token}
            .AddJwtBearer(options =>
            {
                // Prevent automatic mapping of claim types to Microsoft defaults
                options.MapInboundClaims = false;

                options.TokenValidationParameters = new TokenValidationParameters
                {
                    // Validates the token issuer to ensure it was generated by a trusted authority
                    ValidateIssuer = true,
                    ValidIssuer = jwtAuthOptions.Issuer,

                    // Validates the intended audience of the token
                    ValidateAudience = true,
                    ValidAudience = jwtAuthOptions.Audience,

                    // Validates token lifetime
                    ValidateLifetime = true,

                    // Validates token signature using the symmetric security key
                    // Prevents tampering with the token payload
                    ValidateIssuerSigningKey = true,
                    IssuerSigningKey = new SymmetricSecurityKey(
                        Encoding.UTF8.GetBytes(jwtAuthOptions.Key)),

                    // Set which claim represents the user's name
                    NameClaimType = JwtRegisteredClaimNames.Email,

                    // Set which claim represents user roles
                    RoleClaimType = JwtCustomClaimNames.Role
                };
            });

        // Enables authorization policies
        services.AddAuthorization();

        return services;
    }
}
