<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NexaERP.DAL\NexaERP.DAL.csproj" />
  </ItemGroup>
</Project>
